### ISSUE TITLE
add macros to clojure.core ns

### ISSUE THREAD

**Issue by behrica** [AbhinavOmprakash/snitch#28]
I think the macros could be added to the `clojore.core` ns.
then they are available anywhere.

I have done this in this way for another usefull macro:

```
(ns clojure.core)

(defmacro def-let
  "like let, but binds the expressions globally."
  [bindings & more]
  (let [let-expr (macroexpand `(let ~bindings))
        names-values (partition 2 (second let-expr))
        defs   (map #(cons 'def %) names-values)]
    (concat (list 'do) defs more)))
```

It should be possible as well dynamically using "intern"

**Comment by AbhinavOmprakash** [comment]
Whoa! this can be done? I was looking for a solution like this where I don't need to import defn* in every namespace. Thanks, I will look into it :)

**Comment by AbhinavOmprakash** [comment]
I can intern the macros inside the clojure namespace but I can't do this with clojurescript, since clojurescript doesn't support intern. are there any workarounds for this?
